[project]
name = "ts-forecast"
version = "0.1.0"
description = "Project for clustering and forecasting time series data"
authors = [
    {name = "David Grethlein",email = "12dgrethlein@gmail.com"}
]
license = "Apache 2.0"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "torch (==2.2.2)",
    "numpy (<2.0.0)",
    "scikit-learn (>=1.9.1,<2.0.0)",
    "scipy (<1.14.0)",
    "statsmodels (>=0.15.0,<0.16.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "dtaidistance (>=2.5.1,<3.0.0)",
    "sktime (>=1.2.0,<2.0.0)",
    "mlflow (>=3.16.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
